name: 'Cognition Deploy'
description: 'Automatically deploy your JsPsych experiment to Cognition.'
inputs:
  personal-access-token:
    description: 'The token needed to deploy your experiment. Get one at https://www.cognition.run/account'
    required: true
  jspsych-version:
    description: 'JsPsych library version used, e.g., 7.3.0, 6.3.1'
    required: false
outputs:
  link:
    description: 'The link to the task. Share this link with your participants.'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'upload-cloud'
  color: 'blue'